// src/components/PostForm.tsx
import React, { ChangeEvent, useState } from "react";
import { PostType } from "../types/post";
import Card from "./Card";

interface PostFormProps {
  addPost: (post: PostType) => void;
}

function PostForm({ addPost }: PostFormProps) {
  const [body, setBody] = useState("");

  function handleChange(event: ChangeEvent<HTMLInputElement>): void {
    setBody(event.target.value);
  }

  function handleSubmit() {
    addPost({
      id: crypto.randomUUID(),
      body,
    });
    setBody("");
  }

  return (
    <Card
      footer={
        <div className="flex justify-between">
          <button
            className="bg-blue-400 rounded text-white px-4 py-2"
            onClick={handleSubmit}
          >
            Post
          </button>
        </div>
      }
    >
      <div className="flex gap-8">
        <input
          className="w-full leading-loose p-1 focus:outline-none"
          type="text"
          placeholder="What's on your mind?"
          value={body}
          onChange={handleChange}
        />
      </div>
    </Card>
  );
}

export default PostForm;

// newsfeed-app/src/lib/PostForm.svelte
<script>
	import { getContext } from "svelte";
	import Card from "./Card.svelte";
	import Image from "./Image.svelte";

	export let author;

	let content = "";
	const posts = getContext('posts');

	function post() {
		posts.addPost({
			body: content,
			author: author.name,
			authorImageUrl: author.imageUrl
		});
		content = "";
	}
</script>

<Card>
	<div class="flex gap-4">
		<Image src={author.imageUrl} alt={author.name} />

		<input type="text" bind:value={content} placeholder="What is on your mind?" class="w-full leading-loose p-1 focus:outline-none" />
	</div>

	<div slot="footer" class="flex justify-between">
		<button class="bg-black rounded-full text-white text-xs px-4 py-2"><i class="fas fa-photo-video"></i>Photo/Video</button>

		<button class="bg-blue-400 rounded text-white px-4 py-2" on:click={post} disabled={content === ""}>Post It</button>
	</div>
</Card>
