// efuse-app/src/lib/Comment.svelte
<script>
	import dayjs from 'dayjs';
	import relativeTime from 'dayjs/plugin/relativeTime';
	import Image from "./Image.svelte";

	dayjs.extend(relativeTime);

	export let createdAt;
	export let text;
	export let author;
	export let authorImageUrl;
	export let likes;
</script>

<div class="flex items-center my-4">
	<div class="mr-4">
		<Image src={authorImageUrl} alt={author} />
	</div>
	<div class="w-full p-4 bg-gray-300 rounded-lg text-gray-900">
		<div class="flex justify-between w-full mr-8">
			<span class="leading-8 font-medium">{author}</span>
			<span class="leading-8 text-gray-500">{dayjs(createdAt).fromNow()}</span>
		</div>
		<div>
			{text}
		</div>
		<div class="text-gray-500">
			<span class="mr-2">{likes} likes</span> |
			<button class="m-2"><i class="fas fa-heart"></i> Like</button> |
			<button class="m-2"><i class="fas fa-pencil-alt"></i> Edit</button> |
			<button class="m-2"><i class="fas fa-trash"></i> Delete</button>
		</div>
	</div>
</div>

// src/components/Comment.tsx
import dayjs from "dayjs";
import { CommentType } from "../types/comment";

interface CommentProps {
  comment: CommentType;
}

export default function Comment({ comment }: CommentProps) {
  <div>
    <div className="">
      <div className="w-16 h-16 rounded-full flex justify-center items-center bg-red-600"></div>
    </div>
    <div className="flex flex-col justify-center">
      <div className="text text-lg text-gray-900 font-medium">
        {comment.author.name}
      </div>
      <div className="text-xs text-gray-900">
        {dayjs(comment.createdAt).fromNow()}
      </div>
    </div>

    <div></div>
    {comment.body}
  </div>;
}
