// src/lib/CommentForm.svelte
<script>
	import { createEventDispatcher, getContext } from "svelte";

	import Image from "./Image.svelte";

	export let postId;

	const dispatch = createEventDispatcher();
	let author = getContext('user');
	let content = "";

	function addComment() {
		dispatch('addComment', {
			author,
			comment: content,
			postId
		});
		content = "";
	}

	function handleKeydown(event) {
		if(event.keyCode == 13) {
			addComment()
		}
	}
</script>

<div class="flex gap-4">
	<Image src={author.imageUrl} alt={author.name} />

	<input type="text" bind:value={content} placeholder="Add a comment" class="w-full leading-2 rounded-full px-8 py-0.5 focus:outline-none border border-black" on:keydown={handleKeydown} />
</div>

// src/components/CommentForm.tsx
import {
  ChatBubbleLeftIcon,
  PlusCircleIcon,
} from "@heroicons/react/24/outline";
import { ChangeEvent, MouseEvent, useState } from "react";
import { buildComment, CommentType } from "../types/comment";

interface CommentFormProps {
  addComment: (comment: CommentType) => void;
}

function CommentForm({ addComment }: CommentFormProps) {
  const [body, setBody] = useState("");

  function handleChange(event: ChangeEvent<HTMLInputElement>): void {
    setBody(event.target.value);
  }

  function handleSubmit(event: MouseEvent<HTMLButtonElement>) {
    event.preventDefault();

    if (body) {
      addComment(
        buildComment({
          body,
          author: {
            name: "Tim",
          },
        })
      );
      setBody("");
    }
  }

  return (
    <form className="flex justify-between bg-gray-300 rounded-full p-2 mt-4">
      <ChatBubbleLeftIcon className="h-6 w-6 inline text-gray-700" />

      <input
        className="focus:outline-none bg-inherit grow placeholder:text-gray-700 ml-4"
        placeholder="Add comment"
        type="text"
        value={body}
        onChange={handleChange}
      />
      <button
        className="px-1 text-gray-700"
        type="submit"
        onClick={handleSubmit}
      >
        <PlusCircleIcon className="w-6 h-6" />
      </button>
    </form>
  );
}

export default CommentForm;
