// efuse-app/src/lib/Post.svelte
<script lang="ts">
	import Card from "./Card.svelte";
	import dayjs from 'dayjs';
	import relativeTime from 'dayjs/plugin/relativeTime';

	dayjs.extend(relativeTime);

	export let post;

</script>

<Card>
	<div class="header flex my-4">
		<div class="header-image w-16 rounded-full mx-4">
			<img alt="{post.author}" src={post.authorImageUrl} class="rounded-full" />
		</div>
		<div class="flex flex-col header-details">
			<span class="text">{post.author}</span>
			<span class="text-sm text-blue-700">{post.location}</span>
			<span class="text-sm">{dayjs(post.createdAt).fromNow()}</span>
		</div>
	</div>
	<div class="content mx-4">
		<div class="post text-lg my-6">
			{post.body}
		</div>

		<div class="summary">
			<span>{post.likes} Likes</span>
			<span>{post.comments?.length} Comments</span>
		</div>
	</div>

	<svelte:fragment slot="footer">
		<button>Like</button>
		<button>Comment</button>
	</svelte:fragment>
</Card>

// src/components/Post.tsx
import React from "react";
import type { PostType } from "../types/post";
import Card from "./Card";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime.js";
import Comment from "./Comment";

dayjs.extend(relativeTime);

interface PostProps {
  post: PostType;
}

function Post({ post }: PostProps) {
  return (
    <Card>
      <div className="post flex flex-col mb-4">
        <div className="flex my-4 gap-4">
          <div className="">
            <div className="w-16 h-16 rounded-full flex justify-center items-center bg-red-600"></div>
          </div>
          <div className="flex flex-col justify-center">
            <div className="text text-lg text-gray-900 font-medium">
              {post.author.name}
            </div>
            <div className="text-xs text-gray-900">
              {dayjs(post.createdAt).fromNow()}
            </div>
          </div>
        </div>
        <span className="post-body">{post.body}</span>
        <div className="flex gap-4 mt-4">
          <div>
            <span className="font-bold pr-1">{post.likes}</span>
            <span className="text-gray-500">Hypes</span>
          </div>
          <div>
            <span className="font-bold pr-1">{post.comments?.length || 0}</span>{" "}
            <span className="text-gray-500">Comments</span>
          </div>
          <div>
            <span className="font-bold pr-1">{post.shareCount || 0}</span>
            <span className="text-gray-500">Shares</span>
          </div>
          <div>
            <span className="font-bold pr-1">{post.viewCount || 0}</span>
            <span className="text-gray-500">Views</span>
          </div>
        </div>
      </div>

      {post.comments && (
        <div className="comments">
          {post.comments?.map((comment) => (
            <Comment key={comment.id} comment={comment}></Comment>
          ))}
        </div>
      )}
    </Card>
  );
}

export default Post;
